---
- hosts: all
  become: yes
  gather_facts: no
  ignore_errors: true
  vars:
    user_name: koffi95
    color: green

  tasks:
    # - name: install softwares 
    #   package: 
    #     state: present
    #     name: 
    #       - wget
    #       - ntp
    #       - finger
    #       - curl
    # - name: install software 
    #   package:
    #     state: present
    #     name: "{{item}}"
    #     with_items:
    #       - wget
    #       - ntp
    #       - finger
    #       - curl
    - name: check uptime
      command: uptime
      tags: 
        - cm
    - name: install softwares
      package: 
        state: present
        name: "{{item}}"
      loop: 
        - wget
    #    - finger
        - curl


    - name: update
      apt:
        name: passwd
        state: present
      when: ansible_distribution not in "Debian, Ubuntu"
      tags: app1
    - name: create group
      group:
        name: cloudteam
        state: present
#      when: ansible_distribution_major_version < 9
    - name: create user
      user:
        name: "{{user_name}}"
        comment: Koffi Admin
        group: cloudteam
- hosts: db
  become: yes
  gather_facts: no
  tasks:
    - name: install apache
      apt: 
        name: apache2
        state: present
    - name: start service 
      service: name=apache2 state=started enabled=yes
      tags:
        - service
    - name: copy index
      copy:
        src: index.html
        dest: /var/www/html/index.html
        mode: 'o644'

