---
- hosts: all
  become: yes
  gather_facts: no
  ignore_errors: true
  tasks: 
    - name: check uptime
      command: uptime
      register: uptime_output
    - name: create user
      user: 
        name: koffi
        comment: koffi admin
      when: uptime_output.rc != 100
    # - name: Display output
    #   debug:
    #    var: uptime_output.changed

    